INSERT INTO rol (id, nombre)
SELECT 1, 'MEDICO' WHERE NOT EXISTS (SELECT 1 FROM rol WHERE nombre = 'MEDICO');

INSERT INTO rol (id, nombre)
SELECT 2, 'RECEPCIONISTA' WHERE NOT EXISTS (SELECT 1 FROM rol WHERE nombre = 'RECEPCIONISTA');

INSERT INTO rol (id, nombre)
SELECT 3, 'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM rol WHERE nombre = 'ADMIN');