POST http://localhost:8080/evoluciones/crear-diagnostico
Content-Type: application/json

{
  "idHistoriaClinica": 1,
  "nombreDiagnostico": "Fiebre del dengue hemorrágico",
  "evolucionDTO": {
    "plantillaControl": {
      "peso": 70.5,
      "altura": 1.75,
      "presion": "120/60",
      "pulso": 72,
      "saturacion": 98,
      "nivelAzucar": 50
    }
  }
}
